### ISSUE TITLE
Xyce 6.2 is out

### ISSUE THREAD

**Issue by wwoods** [OpenXyce/Xyce#1] opened 2015-08-07 00:28 UTC
Hey, I'm going to create a homebrew (https://github.com/Homebrew/homebrew) formula for this project.  Thanks for the mirror!  However, if you could please pull the next version (I know at least 6.2 is out), that would be great.

**Comment by lutherthecat** [comment] 2015-08-07 02:29
I downloaded and updated both Xyce and Xyce_Regression to version 6.3 from Sandia National Labs.  Note that the docs directory for Xyce was over 200MB.  I deleted the doxygen generated files since they can be recreated easily.  Please let me know if you have any issues with the mirror.

**Comment by wwoods** [comment] 2015-08-07 03:11
Good call, and thanks.  Will do, it might be around 2 weeks before I have
the homebrew working just right (bad timing around a vacation and os
upgrade).

**Comment by lutherthecat** [comment] 2015-11-28 20:42
Closing this ticket.

**Closed** 2015-11-28 20:43 UTC
Labels: enhancement
